project:
  type: website
  output-dir: docs

website:
  title: "Modern Techniques in Modelling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: timetable.qmd
        text: Schedule

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual