project:
  type: website
  output-dir: docs

website:
  title: "Modern Techniques in Modelling"
  navbar:
    left:
      - text: Overview
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Pre-course
        href: 00_PreCourseMaterial.qmd
      - text: Timetable
        href: timetable.qmd

      - text: Practicals
        menu:
          - 03_DiscreteDeterministic_practical.qmd
          - 04_ODEs_practical.qmd
          - 05_Metapop_practical.qmd
          - 06_SensitivitySampling_practical.qmd
          - 08_StochasticIBM_practical.qmd
          - 09_Networks_practical.qmd
          - 10_StochasticContinuous_practical.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual