---
title: "About"
---

## Who we are

Your course organisers are [Oliver Brady](https://www.lshtm.ac.uk/aboutus/people/brady.oliver), [Nicholas Davies](https://www.lshtm.ac.uk/aboutus/people/davies.nicholas), and [Yang Liu](https://www.lshtm.ac.uk/aboutus/people/liu.yang).

Your course administrator is Francesco Grisolia.

Other lectures and demonstrators include [Billy Quilty](https://www.lshtm.ac.uk/aboutus/people/quilty.billy), [Kath O'Reilly](https://www.lshtm.ac.uk/aboutus/people/oreilly.kathleen), [Seb Funk](https://www.lshtm.ac.uk/aboutus/people/funk.sebastian).

## Who you are (= scope of the course)

-   Individuals with some exposure to the theory and use of infectious disease modelling & like to start coding their own models using R **OR**

-   Individuals who know some R but do not have experience using R to code infectious disease models **OR**

-   Individuals who will be conducting research using infectious disease models in R **OR**

-   Individuals who want a deeper understanding of techniques for implementing models.

## Other short courses \@ LSHTM you may be interested in

[Model fitting and inference for infectious disease dynamics](https://www.lshtm.ac.uk/study/courses/short-courses/infectious-diseases-dynamics) (organised by [Seb Funk](https://www.lshtm.ac.uk/aboutus/people/funk.sebastian))

[Introduction to infectious disease modelling and its applications](https://www.lshtm.ac.uk/study/courses/short-courses/infectious-disease-modelling) (organised by Emilia Vynnycky and Richard White)
