---
title: "Modelling problems"
---

## Aim

When you are faced with a research question, and think that modelling might be useful, you have to translate the problem into a model.

As a modeler, you will have to choose the type of model you want to use, build the model and choose the parameters.

In this course, we have 3 sessions (Tuesday and Thursday) to enable you to think constructively about the type of model you might need for a research problem that we provide you with.

We are aiming for a "sketch" of a model or a few ideas of what a model would look like (e.g. compartment diagram). You are not required to code anything.

## Instructions

Tuesday's session (30 mins):

1.  Identify which group you are in and which modelling problem you should tackle (table **TBC**)
2.  Consult your group's Modelling Problem (see below!)
3.  Take some time to look at the problem and ask any questions you need to (20 mins)
4.  Now you've had a chance to think about the problem yourself, you can say "Hi" to your group colleagues

Thursday's session: You'll be working with colleagues in your group to sketch a model that answers your particular question. After this group work, there will be a session to discuss the problem you had to solve, and your ideas for a solution with the other groups. You and your group can write down your ideas on draw.io (link **TBC**).

## The problems

You will be assigned to one of the following four modelling problems.

Your group's assignment is to design a model that could help you complete your task. For instance, you may wish to include the following:

-   A compartment diagram of the disease including demographic states that you wish your model to track (showing arrows between your compartments denoting flows)
-   Any further information on the model set-up (e.g. whether you wish to use a stochastic model and if so what type)
-   A short list of information or parameters that you need to run your model
-   Any values of these parameters needed (you may find googling helpful here - remember to state your source)
-   A short list of where any uncertainty is in your assumptions, model structure or parameter values.

### 1. Avian influenza

A strain of avian influenza is spreading among poultry farms. The virus has a near-100% fatality risk in birds, and has an $R_0$ typically between 1.8 and 2.4 (among birds in a farm setting). Whether $R_0$ is at the low end or the high end of this range seems to depend upon the farm, but the reasons for this variation are not fully understood. When birds are housed outdoors, there is around a 5% risk each year of any given farm having at least one case, but it has been observed that this risk goes up to around 20% if a neighbouring farm has had a substantial outbreak (with more than half of the flock affected). If birds are housed indoors, the risk of introduction is reduced 4-8 fold, because there is reduced contact with wild birds which may spread the virus. You have been asked to model different strategies for reducing the impact of avian influenza on poultry and poultry farms, based around establishing criteria for when birds should be housed inside and when a flock should be culled.

### 2. SARS-CoV-2

Government ministers have asked you to assess the relative efficacy of two alternative quarantine strategies for reducing SARS-CoV-2 transmission. The baseline strategy requires contacts of a suspected COVID-19 case to quarantine for 10 days. The alternative "test-to-release" strategy allows individuals to leave quarantine early if they test negative partway through the quarantine period. Which will be more effective? You have been asked to consider:

-   potentially differing rates of compliance with the two strategies
-   how many days after the start of the quarantine period the "test-to-release" should be taken
-   imperfect sensitivity and specificity of the test

### 3. Dengue

Dengue virus transmits between humans via mosquito vectors. While some infections are asymptomatic, others lead to dengue fever, of which a proportion go on to develop very severe dengue haemorrhagic fever (DHF), which can result in death. There are four subtypes of the dengue virus. Recovering from one subtype generates complete immunity to that subtype (i.e. prevents re-infection) and some immunity to other subtypes (usually termed imperfect cross-immunity). It is also known that second or third dengue infections have a higher chance of DHF due to something called 'antibody-dependent enhancement'. The degree of cross-immunity and increased severity of subsequent infections are highly uncertain, which makes it difficult to understand the impact of intervention strategies.

You are the modeller in a large clinical trial team that is evaluating the use of a dengue vaccine candidate in country Y. Your role is to use a model that will help elucidate the results of the clinical trial which measures the incidence of dengue infection and DHF. However, first, you need to build a model that captures the dynamics of dengue prior to vaccine introduction.

### 4. Seasonal influenza

Country X currently funds an annual influenza vaccination programme (between October and February) that targets school students 6-18 years old. Typically, this school-based programme achieves 40% vaccine coverage among this age group. However, there is no funded programme for working-age adults, who pay for a seasonal flu vaccine themselves (out-of-pocket), and thus the annual coverage levels are typically around 10% in this age group. The government would like to reduce flu-related deaths and hospitalisations each year and is considering whether to try to increase vaccine use and needs to understand the impact of different strategies.

You have been tasked to predict the impact of two potential strategies on flu-related hospitalisations and deaths. The first strategy aims to increase the vaccine coverage among school students using public health campaigns to provide information on flu and vaccines to parents and schools; colleagues in the Immunisation Division believe this campaign would increase the vaccine coverage to 75% given results from a recent pilot study. The second strategy would be to increase vaccine coverage among working-age adults by providing a cash incentive; the effect of this strategy is less certain, but survey results suggest this strategy may increase coverage among working-age adults to around 30%.
