---
title: "Timetable"
toc: true
tbl-colwidths: [15,15,10,45,15]
---

### Day 1

+-------------+-------------+-------------+------------------------------------+--------------+
| Date        | Time        | Session     | Title                              | Lead         |
+=============+=============+=============+====================================+==============+
| 2024/09/09  | 10.00-10.30 | 01          | Introduction                       | Nick Davies  |
|             |             |             |                                    |              |
|             |             |             |                                    | Oli Brady    |
+-------------+-------------+-------------+------------------------------------+--------------+
| Monday      | 10.30-11.00 | 02          | Different types of models          | Oli Brady    |
+-------------+-------------+-------------+------------------------------------+--------------+
|             | 11.00-11.30 |             | BREAK                              |              |
+-------------+-------------+-------------+------------------------------------+--------------+
|             | 11.30-12.30 | 03          | Discrete-time deterministic models | Billy Quilty |
+-------------+-------------+-------------+------------------------------------+--------------+
|             | 12.30-13.30 |             | LUNCH                              |              |
+-------------+-------------+-------------+------------------------------------+--------------+
|             | 13.30-14.30 | 03          | Discrete-time deterministic models | Billy Quilty |
+-------------+-------------+-------------+------------------------------------+--------------+
|             | 14.30-15.00 |             | BREAK                              |              |
+-------------+-------------+-------------+------------------------------------+--------------+
|             | 15.00-16.00 | 04          | ODE models                         | Nick Davies  |
+-------------+-------------+-------------+------------------------------------+--------------+

### Day 2

+-------------+-------------+-------------+---------------------------------------+-------------+
| Date        | Time        | Session     | Title                                 | Lead        |
+=============+=============+=============+=======================================+=============+
| 2024/09/10  | 10.00-11.30 | 04          | ODE models (continued)                | Nick Davies |
+-------------+-------------+-------------+---------------------------------------+-------------+
| Tuesday     | 11.30-12.00 |             | BREAK                                 |             |
+-------------+-------------+-------------+---------------------------------------+-------------+
|             | 12.00-12.45 | 05          | Metapopulations with ODEs             | Nick Davies |
+-------------+-------------+-------------+---------------------------------------+-------------+
|             | 12.45-13.30 |             | LUNCH                                 |             |
+-------------+-------------+-------------+---------------------------------------+-------------+
|             | 13.30-15.00 | 06          | Simulation, sensitivity, and sampling | Yang Liu    |
+-------------+-------------+-------------+---------------------------------------+-------------+
|             | 15.00-15.30 |             | BREAK                                 |             |
+-------------+-------------+-------------+---------------------------------------+-------------+
|             | 15.30-16.00 | 07          | Presentation of modelling problem     | Yang Liu    |
+-------------+-------------+-------------+---------------------------------------+-------------+

### Day 3

+-------------+-------------+-------------+------------------------------------+---------------+
| Date        | Time        | Session     | Title                              | Lead          |
+=============+=============+=============+====================================+===============+
| 2024/09/11  | 10.00-11.00 | 08          | Stochastic individual-based models | Nick Davies   |
+-------------+-------------+-------------+------------------------------------+---------------+
| Wednesday   | 11.00-11.30 |             | BREAK                              |               |
+-------------+-------------+-------------+------------------------------------+---------------+
|             | 11.30-12.30 | 08          | Stochastic individual-based models | Nick Davies   |
+-------------+-------------+-------------+------------------------------------+---------------+
|             | 12.30-13.30 |             | LUNCH                              |               |
+-------------+-------------+-------------+------------------------------------+---------------+
|             | 13.30-14.30 | 09          | Network models                     | Kath O'Reilly |
+-------------+-------------+-------------+------------------------------------+---------------+
|             | 14.30-15.00 |             | BREAK                              |               |
+-------------+-------------+-------------+------------------------------------+---------------+
|             | 15.00-16.00 | 09          | Network models                     | Kath O'Reilly |
+-------------+-------------+-------------+------------------------------------+---------------+

### Day 4

+-------------+-------------+-------------+-----------------------------------+---------------+
| Date        | Time        | Session     | Title                             | Lead          |
+=============+=============+=============+===================================+===============+
| 2024/09/12  | 10.00-11.00 | 10          | Stochastic continuous-time models | Seb Funk      |
+-------------+-------------+-------------+-----------------------------------+---------------+
| Thursday    | 11.00-11.30 |             | BREAK                             |               |
+-------------+-------------+-------------+-----------------------------------+---------------+
|             | 11.30-12.30 | 10          | Stochastic continuous-time models | Seb Funk      |
+-------------+-------------+-------------+-----------------------------------+---------------+
|             | 12.30-13.30 |             | LUNCH                             |               |
+-------------+-------------+-------------+-----------------------------------+---------------+
|             | 13.30-14.30 | 11          | Group work                        | Seb Funk      |
+-------------+-------------+-------------+-----------------------------------+---------------+
|             | 14.30-14.45 |             | BREAK                             |               |
+-------------+-------------+-------------+-----------------------------------+---------------+
|             | 14.45-15.45 | 12          | Group presentations               | Seb Funk      |
+-------------+-------------+-------------+-----------------------------------+---------------+
|             | 15.45-16.15 | 13          | Wrap-up                           | Yang/Nick/Oli |
+-------------+-------------+-------------+-----------------------------------+---------------+
